export default {
  FONT_LOGO: 'Ketimun-Medium',
  // FONT_FAMILY: 'Montserrat-Regular',
  // FONT_BOLD: 'Montserrat-Bold',
  FONT_FAMILY: 'Nunito-Regular',
  FONT_BOLD: 'Nunito-Bold',
  // FONT_BOLD_ITALIC: 'Montserrat-Bold',
  // FONT_ITALIC: 'Montserrat-Regular',
  // FONT_LIGHT: 'Montserrat-Regular',
  // FONT_LIGHT_ITALIC: 'Montserrat-Regular',
  // FONT_MEDIUM: 'Montserrat-Regular',
  // FONT_MEDIUM_ITALIC: 'Montserrat-Regular',
  // FONT_REGULAR: 'Montserrat-Regular',
  // FONT_SEMI_BOLD: 'Montserrat-Bold',
  // FONT_SEMI_BOLD_ITALIC: 'Montserrat-Bold',
};
